<?php
/**
 * Файл с демо-данными для модуля qwelp.site_settings
 */

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

return [
    [
        'NAME' => 'Общие', 'CODE' => 'general', 'SORT' => 100, 'UF_FIELDS' => [], 'ELEMENTS' => [],
        'SUBSECTIONS' => [
            [
                'NAME' => 'Основные', 'CODE' => 'general_main', 'SORT' => 110, 'UF_FIELDS' => [], 'ELEMENTS' => [],
                'SUBSECTIONS' => [
                    ['NAME' => 'Оформление', 'CODE' => 'oformlenie', 'SORT' => 100, 'UF_FIELDS' => ['UF_SECTION_TOOLTIP' => 'Подсказка раздел фывфыв фывфыв'], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Оформление элементы', 'CODE' => 'oformlenie-elementy', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"Автоматически","label":"Автоматически"},{"value":"Светлое","label":"Светлое"},{"value":"Темное","label":"Темное"}]}', 'DESCRIPTION' => '']]]]],
                    ['NAME' => 'Базовый цвет', 'CODE' => 'bazovyy-tsvet', 'SORT' => 200, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Базовый цвет элементы', 'CODE' => 'bazovyy-tsvet-elementy', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"color":[{"value":"#dc2f2f"},{"value":"#f35c50"},{"value":"#f2722c"},{"value":"#fd9c12"},{"value":"#ffb400"},{"value":"#83b81d"},{"value":"#08a826"},{"value":"#0aa360"},{"value":"#00aea0"},{"value":"#13b3f8"},{"value":"#2196e0"},{"value":"#257de3"},{"value":"#365edc"},{"value":"#5555dc"},{"value":"#a447bf"},{"value":"#78627f"},{"value":"#da3b64"},{"value":"#d2334d"}]}', 'DESCRIPTION' => ''], 'PERCENT' => '80%']]]],
                    ['NAME' => 'Дополнительный цвет', 'CODE' => 'dopolnitelnyy-tsvet', 'SORT' => 300, 'UF_FIELDS' => ['UF_HIDDEN_CHECKBOX' => 1], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Дополнительный цвет элемент', 'CODE' => 'dopolnitelnyy-tsvet-element', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"color":[{"value":"#000000","label":"1"},{"value":"#a14545","label":"2"}]}', 'DESCRIPTION' => ''], 'HIDDEN_CHECKBOX' => 'Y']]]],
                    ['NAME' => 'Цвет текста кнопок', 'CODE' => 'tsvet-teksta-knopok', 'SORT' => 400, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Цвет текста кнопок элементы', 'CODE' => 'tsvet-teksta-knopok-elementy', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"color":[{"value":"#000000","label":"1"},{"value":"#a14545","label":"2"}]}', 'DESCRIPTION' => ''], 'HIDDEN_CHECKBOX' => 'Y']], ['NAME' => 'Цвет текста кнопок элементы11111', 'CODE' => 'tsvet-teksta-knopok-elementy11111', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"1","label":"1"},{"value":"2","label":"2"},{"value":"3","label":"4"}]}', 'DESCRIPTION' => ''], 'HIDDEN_CHECKBOX' => 'Y']], ['NAME' => 'Цвет текста кнопок элементы1', 'CODE' => 'tsvet-teksta-knopok-elementy111', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"1","label":"1"},{"value":"2","label":"2"},{"value":"3","label":"4"}]}', 'DESCRIPTION' => ''], 'HIDDEN_CHECKBOX' => 'Y']]]],
                    ['NAME' => 'Ширина сайта', 'CODE' => 'shirina-sayta', 'SORT' => 500, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Ширина сайта', 'CODE' => 'shirina-sayta', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"1696","label":"1 696 px"},{"value":"1464","label":"1 464 px"},{"value":"1296","label":"1 296 px"}]}', 'DESCRIPTION' => '']]]]],
                    ['NAME' => 'Шрифт', 'CODE' => 'shrift', 'SORT' => 600, 'UF_FIELDS' => ['UF_COMMON_PROPERTY' => 1], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Golos Text', 'CODE' => 'golos-text', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"15","label":"15 px"},{"value":"16","label":"16 px"},{"value":"17","label":"17 px"}]}', 'DESCRIPTION' => '']]], ['NAME' => 'Manrope', 'CODE' => 'manrope', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"15","label":"15 px"},{"value":"16","label":"16 px"},{"value":"17","label":"17 px"}]}', 'DESCRIPTION' => '']]], ['NAME' => 'Rubik', 'CODE' => 'rubik', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"15","label":"15 px"},{"value":"16","label":"16 px "},{"value":"17","label":"17 px"}]}', 'DESCRIPTION' => '']]], ['NAME' => 'Wix Madefor Text', 'CODE' => 'wix-madefor-text', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"15","label":"15 px"},{"value":"16","label":"16 px "},{"value":"17","label":"17 px"}]}', 'DESCRIPTION' => ''], 'HELP_TEXT' => 'Текст подсказки 123']]]],
                    ['NAME' => 'Другой шрифт заголовков', 'CODE' => 'drugoy-shrift-zagolovkov', 'SORT' => 700, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Другой шрифт заголовков элемент', 'CODE' => 'drugoy-shrift-zagolovkov-element', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => '']]]]],
                    ['NAME' => 'Скругление кнопок', 'CODE' => 'skruglenie-knopok', 'SORT' => 800, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Скругление кнопок элемент', 'CODE' => 'skruglenie-knopok-element', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radio":[{"value":"0px","label":"0px"},{"value":"6px","label":"6px"},{"value":"8px","label":"8px"},{"value":"12px","label":"12px"},{"value":"16px","label":"16px"},{"value":"20px","label":"20px"},{"value":"24px","label":"24px"}]}', 'DESCRIPTION' => '']]]]],
                    ['NAME' => 'Внутреннее меню', 'CODE' => 'vnutrennee-menyu', 'SORT' => 900, 'UF_FIELDS' => [], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Внутреннее меню элементы', 'CODE' => 'vnutrennee-menyu-elementy', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"radioImage":[{"value":"left","label":"Слева","fileId":1366},{"value":"right","label":"Справа","fileId":1367}]}', 'DESCRIPTION' => '']]]]],
                ]
            ]
        ]
    ],
    [
        'NAME' => 'Главная', 'CODE' => 'glavnaya', 'SORT' => 200, 'UF_FIELDS' => [], 'ELEMENTS' => [],
        'SUBSECTIONS' => [
            [
                'NAME' => 'Блоки', 'CODE' => 'bloki', 'SORT' => 500, 'UF_FIELDS' => ['UF_ENABLE_DRAG_AND_DROP' => 1], 'ELEMENTS' => [],
                'SUBSECTIONS' => [
                    ['NAME' => 'Бренды', 'CODE' => 'brendy', 'SORT' => 500, 'UF_FIELDS' => ['UF_HIDDEN_ELEMENTS_TITLE' => 'настроенное название 12132123', 'UF_DETAIL_PROPERTY' => 1, 'UF_COLLAPSED_BLOCK' => 1, 'UF_SECTION_TOOLTIP' => 'вапвапвапвп'], 'SUBSECTIONS' => [['NAME' => 'Плиткой', 'CODE' => 'plitkoy-br', 'SORT' => 500, 'UF_FIELDS' => ['UF_HIDDEN_ELEMENTS_TITLE' => 'настроенное название'], 'ELEMENTS' => [['NAME' => 'С обводкой', 'CODE' => 's-obvodkoy', 'SORT' => 100, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y']], ['NAME' => 'С фоном', 'CODE' => 's-fonom', 'SORT' => 200, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']], ['NAME' => 'Количество строк', 'CODE' => 'kolichestvo-strok', 'SORT' => 300, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"10","label":"10"},{"value":"20","label":"20"},{"value":"30","label":"30"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']]], 'SUBSECTIONS' => []], ['NAME' => 'Каруселью', 'CODE' => 'karuselyu-br', 'SORT' => 500, 'UF_FIELDS' => ['UF_SECTION_TOOLTIP' => 'Подсказка раздел фывфыв фывфыв'], 'ELEMENTS' => [['NAME' => 'С обводкой', 'CODE' => 's-obvodkoy-br-k', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'HEADER_TITLE' => 'Y']], ['NAME' => 'С фоном', 'CODE' => 's-fonom-k-br', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'HEADER_TITLE' => 'Y']]], 'SUBSECTIONS' => []]], 'ELEMENTS' => [['NAME' => 'Верхний отступ', 'CODE' => 'verkhniy-otstup', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"10","label":"10"},{"value":"20","label":"20"},{"value":"30","label":"30"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y']], ['NAME' => 'Нижний отступ', 'CODE' => 'nizhniy-otstup', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"10","label":"10"},{"value":"20","label":"20"},{"value":"30","label":"30"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y', 'HEADER_TITLE' => 'Y']], ['NAME' => 'Фон', 'CODE' => 'fon', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y', 'HEADER_TITLE' => 'Y']], ['NAME' => 'Разделитель', 'CODE' => 'razdelitel', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y', 'HEADER_TITLE' => 'Y']]]],
                    ['NAME' => 'Образы', 'CODE' => 'obrazy', 'SORT' => 500, 'UF_FIELDS' => ['UF_DETAIL_PROPERTY' => 1, 'UF_COLLAPSED_BLOCK' => 1], 'SUBSECTIONS' => [], 'ELEMENTS' => [['NAME' => 'Верхний отступ', 'CODE' => 'verkhniy-otstup-ob', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"10","label":"10"},{"value":"20","label":"20"},{"value":"30","label":"30"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y']], ['NAME' => ' Нижний отступ', 'CODE' => 'nizhniy-otstup-ob', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"10","label":"10"},{"value":"20","label":"20"},{"value":"30","label":"30"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']]]],
                    ['NAME' => 'Тизеры', 'CODE' => 'tizery', 'SORT' => 500, 'UF_FIELDS' => ['UF_HIDDEN_ELEMENTS_TITLE' => 'Состав тизера', 'UF_COLLAPSED_BLOCK' => 1], 'SUBSECTIONS' => [['NAME' => 'Карточкой', 'CODE' => 'kartochkoy2134213', 'SORT' => 500, 'UF_FIELDS' => [], 'ELEMENTS' => [], 'SUBSECTIONS' => []]], 'ELEMENTS' => [['NAME' => 'Верхний отступ', 'CODE' => 'verkhniy-otstup2312', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"0","label":"0"},{"value":"12","label":"12"},{"value":"24","label":"24"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']], ['NAME' => 'Нижний отступ', 'CODE' => 'nizhniy-otstupdasad', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"select":[{"value":"0","label":"0"},{"value":"12","label":"12"},{"value":"24","label":"24"}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y', 'DETAIL_PROPERTY' => 'Y']], ['NAME' => 'С обводкой', 'CODE' => 's-obvodkoy12', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']], ['NAME' => 'С фоном', 'CODE' => 's-fonom1231231', 'SORT' => 500, 'PROPERTIES' => ['VALUES' => ['VALUE' => '{"checkbox":[{}]}', 'DESCRIPTION' => ''], 'SHOW_TITLE' => 'Y']]]],
                ]
            ]
        ]
    ],
];
